# En son Ubuntu imajını kullan
FROM ubuntu:latest

# APT'yi güncelle ve sistemdeki paketleri yükselt
RUN apt-get update && apt-get upgrade -y

# Konteyner çalıştığında "Hello, World!" yazdır
CMD ["echo", "Hello, World!"]
